name: Approve Command Trigger
on:
  issue_comment:
    types: [created]

jobs:
  approve-command-trigger:
    if: contains(github.event.issue.labels.*.name, 'new-model')
    runs-on: ubuntu-latest
    steps:
      - name: Approve Command Trigger
        uses: peter-evans/slash-command-dispatch@v4.0.0
        with:
          token: ${{ secrets.PAT }}
          issue-type: issue
          permission: write
          reactions: false
          commands: |
            approve
