name: Test Ersilia codebase

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  # 1. Run Ruff formatting
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Ruff
        run: pip install ruff

      - name: Run Ruff
        run: ruff check --output-format=github .

  # 2. Run pytest
  run-pytest:
    runs-on: ubuntu-latest
    needs: ruff-format
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10.10"

      - name: Install dependencies
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install -e .[test]

      - name: Run pytest
        run: |     
          pip install pytest pytest-benchmark pytest-asyncio rdkit-pypi nox rich fuzzywuzzy scipy pyairtable
          pytest

  # 3. Install ersilia in ubuntu and macos and test basic model in several python versions
  test-matrix:
    needs: run-pytest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -el {0}  # Required for conda activation

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge

      - name: Install Ersilia from source
        run: |
          python --version
          python -m pip install -e .

      - name: Test Ersilia CLI
        run: |
          ersilia --help
          ersilia --version
      
      - name: Test catalog
        run: |
          ersilia catalog --hub
          ersilia catalog --local

      - name: Fetch model from GitHub
        run: |
          ersilia -v fetch molecular-weight --from_github
          echo "Serving molecular-weight model."
          ersilia serve molecular-weight --track --no-cache
          ersilia info
          ersilia run -i "CC(=O)OC1=CC=CC=C1C(=O)O" | grep "180.15899"
          ersilia close

      - name: Fetch model from S3
        run: |
          ersilia -v fetch molecular-weight --from_s3
          echo "Serving molecular-weight model."
          ersilia serve molecular-weight --track --no-cache
          ersilia info
          ersilia run -i "CC(=O)OC1=CC=CC=C1C(=O)O" | grep "180.15899"
          ersilia close

      - name: Fetch model from Dockerhub
        run: |
          ersilia -v fetch molecular-weight --from_dockerhub
          echo "Serving molecular-weight model."
          ersilia serve molecular-weight --track --no-cache
          ersilia info
          ersilia run -i "CC(=O)OC1=CC=CC=C1C(=O)O" | grep "180.15899"
          ersilia close

  run-default-cli-test:
    needs: test-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install dependencies
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install -e .[test]

      - name: Run Default Default
        run: |
          nox -f test/playground/noxfile.py -s execute -p 3.12

  run-cli-test-multiple:
    needs: run-default-cli-test
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10.10"

      - name: Install dependencies
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install -e .[test]

      - name: Run CLI Test Multiple
        run: |          
          nox -f test/playground/noxfile.py -s execute -p 3.12 -- --cli serve --fetch from_dockerhub --runner multiple --silent false

  generate-nox-parl-jobs:
      needs: run-cli-test-multiple
      outputs:
        session: ${{ steps.set-matrix.outputs.session }}
      defaults:
        run:
          shell: bash -el {0}
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: conda-incubator/setup-miniconda@v3
          with:
            auto-update-conda: true
            python-version: "3.12"

        - name: Install dependencies
          run: |
            conda install git-lfs -c conda-forge
            git-lfs install
            conda install gh -c conda-forge
            python -m pip install -e .[test]
      
        - id: set-matrix
          run: echo "session=$(nox -f test/playground/noxfile.py --json -l 2>&1 | tail -n 1 | jq -c '[.[].session]')" | tee --append $GITHUB_OUTPUT

  run-cli-test-parallel:
    name: Session ${{ matrix.session }} on ${{ matrix.os }} - Fetch ${{ matrix.fetch_source }}
    needs: generate-nox-parl-jobs
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        session: ${{ fromJson(needs.generate-nox-parl-jobs.outputs.session) }}
        fetch_source: ["from_github", "from_s3", "from_dockerhub"]

        exclude:
          - os: macos-latest
            fetch_source: from_dockerhub  
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install dependencies
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install -e .[test]

      - run: |
          nox -f test/playground/noxfile.py -s "${{ matrix.session }}" -- --cli fetch serve run --fetch ${{ matrix.fetch_source }} --host gh

  test-colab-notebook:
    needs: run-pytest
    defaults:
      run:
        shell: bash -el {0}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.12"

      - name: Install dependencies
        run: |
          conda install google-colab -c conda-forge
          pip install --upgrade nbconvert nbformat jsonschema pandas jupyter
          jupyter --version

      - name: Test Google Colab Notebook with CLI shell commands
        run: |
          jupyter nbconvert --to notebook --execute notebooks/test-colab-notebook-cli.ipynb --output=output-cli.ipynb --ExecutePreprocessor.timeout=-1

      - name: Test Google Colab Notebook with Python API commands
        run: |
          echo "Skipping Python API notebook due to unresolved issue"
          #jupyter nbconvert --to notebook --execute notebooks/test-colab-notebook-python-api.ipynb --output=output-python-api.ipynb --ExecutePreprocessor.timeout=-1

      - name: Upload Output of the Google Colab Notebook CLI
        uses: actions/upload-artifact@v4.5.0
        with:
          name: output-cli.ipynb
          path: notebooks/output-cli.ipynb
          retention-days: 7

  update-model-request_template:
    needs: run-pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Path Filter
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            tag-file:
              - 'ersilia/hub/content/metadata/tag.txt'

      - name: Set up Python
        if: steps.filter.outputs.tag-file == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        if: steps.filter.outputs.tag-file == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Run update_model_request_template.py
        if: steps.filter.outputs.tag-file == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/update_model_request_template.py

      - name: Commit and push changes
        if: steps.filter.outputs.tag-file == 'true'
        uses: actions-js/push@v1.5
        with:
          author_name: "ersilia-bot"
          author_email: "ersilia-bot@users.noreply.github.com"
          message: "Update model request template [skip ci]"
          repository: "ersilia-os/ersilia"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
          branch: "master"